development:
  adapter: postgresql
  encoding: unicode
  database: tradeship_development11
  host: localhost
  pool: 5
  username: postgres
  password:  123456

test:
  adapter: postgresql
  encoding: unicode
  database: tradeship_test11
  host: localhost
  pool: 5
  username: postgres
  password: 123456


production:
  adapter: postgresql
  encoding: unicode
  database: tradeship11
  host: localhost
  pool: 5
  username: root
  password: 
   
